{
  "hash": "f0d2252c3e013f4718ec63ce69e813ae",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"How do environmental stressors and resource availability influence reproductive success of an urban adapring songbird?\"\nauthor: Me\ndate: today\ntoc: true\nabstract-titel: \"Our Hypothesis:\"\nabstract: \"- With higher insect abundance and lower noise levels we expect to encounter more fledglings. \\n - We expect to see less insect abundance with inccreasing environmental noise\"\n\nproject:\n  output-dir: output\n  execute-dir: project\n\nformat:\n  html:\n    embed-resources: true\n    number-sections: true\n    code-fold: true\n    comments: \n      hypothesis: true\n    \neditor: visual\neditor_options:\n  chunk_output_types: console\n\nexecute:\n  warning: false\n  error: false\n  freeze: true\n---\n\n# Preparing session\n\n\n::: {.cell}\n\n:::\n\n\n## Explore data - Numerically\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor_insect_vs_noise<-cor(urb_fledg$insect_abundance_g_m_2, urb_fledg$environmental_noise_dB)\n#strong negative correlation\n```\n:::\n\n\nWe have a negative correlation of -0.78 which means that there is an interaction between the environmental noise and insect abundance.\n\n## Explore data - Graphically\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggarrange(\n  ggplot(urb_fledg, aes(x=environmental_noise_dB, y=number_of_fledglings))+\n    geom_point()+\n    geom_smooth(method=\"lm\")+\n    xlab(\"Enrironmental noise (dB)\")+\n    ylab(\"Number of fledglings\")\n  ,\n  \n  ggplot(urb_fledg, aes(x=insect_abundance_g_m_2, y=number_of_fledglings))+\n    geom_point()+\n    geom_smooth(method=\"lm\")+\n    xlab(\"Insect abundance (g/m^2)\")+\n    ylab(\"Number of fledglings\"),\n  \n  ggplot(urb_fledg, aes(x=insect_abundance_g_m_2, y=environmental_noise_dB))+\n    geom_point()+\n    geom_smooth(method=\"lm\")+\n    xlab(\"Insect abundance (g/m^2)\")+\n    ylab(\"noise\"),\n  common.legend = TRUE, labels=c(\"a)\", \"b)\", \"c)\")\n  \n)\n```\n\n::: {.cell-output-display}\n![Exploratory plots; a) higher environmental noise (dB) is associated with fewer fledglings; b) higher insect abundance (g/m^2) is associated with a greater number of fledglings; c) higher environemntal nosie (dB) is associated with a lower insect abundace (g(m^2))](Analysis_urban_fledg_files/figure-html/fig-exp-graph-1.png){#fig-exp-graph width=1133.85826771654}\n:::\n:::\n\n\nAs we can see in the @fig-exp-graph we have a positive correlation between the number of fledglings and the insect abundance, a negative correlation between the environmental noise and the number of fledglings as well as between environmental noise and insect abundance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(urb_fledg, aes(x=insect_abundance_g_m_2, y=environmental_noise_dB))+\n  geom_point(aes(size=number_of_fledglings, color=number_of_fledglings), alpha=.7)+\n  xlab(\"Insect abundance (g/m^2)\")+\n  ylab(\"Environmental noise (dB)\")\n```\n\n::: {.cell-output-display}\n![Insect abundance plotted against environmental noise, with point size representing the number of fledglings.](Analysis_urban_fledg_files/figure-html/fig-common-plot-1.png){#fig-common-plot width=672}\n:::\n:::\n\n\nOnce again we plot it all togheter for completeness in @fig-common-plot.\n\n# Fit the models\n\n## Fit candidate models\n\n\n::: {#tbl-candidate-models .cell tbl-cap='Candidate model comparisons'}\n\n```{.r .cell-code}\nmodel.00<-glm(number_of_fledglings~1, urb_fledg, family=poisson)\nmodel.01<-glm(number_of_fledglings~insect_abundance_g_m_2, urb_fledg, family=poisson)\nmodel.02<-glm(number_of_fledglings~insect_abundance_g_m_2+environmental_noise_dB, urb_fledg, family=poisson)\nmodel.03<-glm(number_of_fledglings~insect_abundance_g_m_2*environmental_noise_dB, urb_fledg, family=poisson)\n\nknitr::kable(compare_performance(model.00, model.01, model.02, model.03), digits=3)\n```\n\n::: {.cell-output-display}\n\n\n|Name     |Model |     AIC| AIC_wt|    AICc| AICc_wt|     BIC| BIC_wt| R2_Nagelkerke|  RMSE| Sigma| Score_log| Score_spherical|\n|:--------|:-----|-------:|------:|-------:|-------:|-------:|------:|-------------:|-----:|-----:|---------:|---------------:|\n|model.00 |glm   | 143.887|  0.004| 143.998|   0.005| 145.524|  0.012|         0.000| 1.275|     1|    -1.867|           0.160|\n|model.01 |glm   | 133.798|  0.656| 134.141|   0.708| 137.073|  0.827|         0.932| 0.341|     1|    -1.708|           0.161|\n|model.02 |glm   | 135.743|  0.248| 136.448|   0.223| 140.655|  0.138|         0.936| 0.330|     1|    -1.707|           0.161|\n|model.03 |glm   | 137.729|  0.092| 138.941|   0.064| 144.279|  0.023|         0.937| 0.328|     1|    -1.707|           0.161|\n\n\n:::\n\n```{.r .cell-code}\nmodel.04<-glm(insect_abundance_g_m_2~environmental_noise_dB, urb_fledg, family=poisson())\n```\n:::\n\n\n\n# Check model diagnostics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#check overdispersion\n\ncheck_overdispersion(model.02)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio = 0.029\n  Pearson's Chi-Squared = 1.005\n                p-value =     1\n```\n\n\n:::\n:::\n\n\nNo issues with overdispersion.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(model.02)\n```\n\n::: {.cell-output-display}\n![Diagnostic plots](Analysis_urban_fledg_files/figure-html/fig-diagnostic-model-1.png){#fig-diagnostic-model width=944.88188976378}\n:::\n:::\n\n\nIn @fig-diagnostic-model we can see that there appears to be no high collinearity between the variables, the homoscedasticity assumption is also met as well as the Normality (normal residuals distribution) and Linearity(trends in the residuals). Also we can detect no outliers/influencial points in the Cook's plot.\n\n## Interpret the chosen model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoef_table_03<-round(summary(model.03)$coefficients,3)\ncoef_table_02<-round(summary(model.02)$coefficients,3)\n\n\nr.2<-round(attributes(r.squaredLR(model.02))$adj.r.squared,3)\n\nnull_chi<-anova(model.00, model.02)\n\n\n## Interaction plot -----\npred.both<-predict_response(model.02, terms=c(\"insect_abundance_g_m_2\", \"environmental_noise_dB\"))\n\npred.both$group<-factor(pred.both$group, labels=c(\"min\", \"mean\", \"max\"))\n  \n  # Create plot\nggplot(pred.both, aes(x=x, y=predicted)) +\n    geom_point(data= urb_fledg, aes(y=number_of_fledglings, x=insect_abundance_g_m_2, size= number_of_fledglings), alpha= .4) +\n    geom_ribbon(aes(ymin= conf.low, ymax= conf.high,\n                    fill= group), alpha= .2) +\n    geom_line(aes(col= group))+\n  labs(\n    color = \"Environmental noise (dB)\",\n    fill = \"Environmental noise (dB)\",\n    size = \"Number of fledglings\"\n  )+\n  xlab(\"Insect abundance (g/m^2)\")+\n  ylab(\"Number of fledgling\")\n```\n\n::: {.cell-output-display}\n![Predicted number of fledglings based on insect abundance (g/m^2) for each environmental noise category: min, mean, max (dB)](Analysis_urban_fledg_files/figure-html/fig-pred-plot-1.png){#fig-pred-plot width=672}\n:::\n:::\n\n\n\n::: {#tbl-glm .cell tbl-cap='Estimates, associated standard errors and statistical significance of the parameters estimated by a poisson GLM ($R^2$= 0.28 , $\\chi^2_{( 2 , 35 )}$= 12.144 , $p$ = 0.002 )'}\n\n```{.r .cell-code}\nknitr::kable(coef_table_02)\n```\n\n::: {.cell-output-display}\n\n\n|                       | Estimate| Std. Error| z value| Pr(>&#124;z&#124;)|\n|:----------------------|--------:|----------:|-------:|------------------:|\n|(Intercept)            |    0.896|      1.417|   0.632|              0.527|\n|insect_abundance_g_m_2 |    0.083|      0.041|   2.043|              0.041|\n|environmental_noise_dB |   -0.004|      0.018|  -0.236|              0.814|\n\n\n:::\n:::\n\n\nA poisson Generalized Linear Model (*R*^2^= 0.28 , $\\chi^2_{( 2 , 35 )}$= 12.144 , *p*= 0.0023064; @tbl-glm) performed significantly better than a null model, compromising an intercept only.  We see a signigicance for the insect abundance variable, explaining number of fledglings found in a nest.($\\beta_{insect}$= 0.083 , *SE*= 0.041 , *z*= 2.043, *p*= 0.041)\nBut for the environmental noise no significance in predicting the number of fledglings. ($\\beta_{noise}$= -0.004 , *SE*= 0.018 , *z*= -0.236, *p*= 0.814) \n\nThe model with an interaction term (@tbl-candidate-models) $model.03$) did not generate compelling support for our prior hypothesized interaction between insect abundance and environmental noise ($\\beta_{insect: noise}$= 0.001 , *SE*= 0.005 , *z*= 0.117, *p*= 0.907) on the number of fledglings found in a nest.\n\n",
    "supporting": [
      "Analysis_urban_fledg_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}